name: fixithub
description: "FixItHub is Where you can get your devices back to life by just a button click"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  iconsax: ^0.0.8
  dio: ^5.8.0+1
  dartz: ^0.10.1
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  get_storage: ^2.1.1
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1
  pretty_dio_logger: ^1.4.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#F5F5F5"
  color_dark: "#1F2937"

  android_12:
    color: "#F5F5F5"
    color_dark: "#1F2937"
